/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeekRouteImport } from './routes/_app.week'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as AppToxicLoadRouteImport } from './routes/_app.toxic-load'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppStartHereRouteImport } from './routes/_app.start-here'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoutinesRouteImport } from './routes/_app.routines'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProgramDatesRouteImport } from './routes/_app.program-dates'
import { Route as AppPrintCenterRouteImport } from './routes/_app.print-center'
import { Route as AppPantryAuditRouteImport } from './routes/_app.pantry-audit'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppMovementRouteImport } from './routes/_app.movement'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppHardDayRouteImport } from './routes/_app.hard-day'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCaregiverRouteImport } from './routes/_app.caregiver'
import { Route as AppBreathworkRouteImport } from './routes/_app.breathwork'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppActionPlanRouteImport } from './routes/_app.action-plan'
  import { Route as AppEducationRouteImport } from './routes/_app.education'
  import { Route as AppSubstitutesRouteImport } from './routes/_app.substitutes'
  import { Route as AppHempRouteImport } from './routes/_app.hemp'
  import { Route as AppHandoutsRouteImport } from './routes/_app.handouts'
import { Route as AppResourcesIndexRouteImport } from './routes/_app.resources.index'
import { Route as AppRecipesIndexRouteImport } from './routes/_app.recipes.index'
import { Route as AppPhasesIndexRouteImport } from './routes/_app.phases.index'
import { Route as AppLearningIndexRouteImport } from './routes/_app.learning.index'
import { Route as AppBrainGamesIndexRouteImport } from './routes/_app.brain-games.index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app.appointments.index'
import { Route as AppResourcesIdRouteImport } from './routes/_app.resources.$id'
import { Route as AppRecipesIdRouteImport } from './routes/_app.recipes.$id'
import { Route as AppPhasesSlugRouteImport } from './routes/_app.phases.$slug'
import { Route as AppLearningIdRouteImport } from './routes/_app.learning.$id'
import { Route as AppBrainGamesIdRouteImport } from './routes/_app.brain-games.$id'
import { Route as AppAppointmentsRequestRouteImport } from './routes/_app.appointments.request'
import { Route as AppAdminResourcesRouteImport } from './routes/_app.admin.resources'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeekRoute = AppWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppToxicLoadRoute = AppToxicLoadRouteImport.update({
  id: '/toxic-load',
  path: '/toxic-load',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppStartHereRoute = AppStartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramDatesRoute = AppProgramDatesRouteImport.update({
  id: '/program-dates',
  path: '/program-dates',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintCenterRoute = AppPrintCenterRouteImport.update({
  id: '/print-center',
  path: '/print-center',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryAuditRoute = AppPantryAuditRouteImport.update({
  id: '/pantry-audit',
  path: '/pantry-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementRoute = AppMovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHardDayRoute = AppHardDayRouteImport.update({
  id: '/hard-day',
  path: '/hard-day',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppBreathworkRoute = AppBreathworkRouteImport.update({
  id: '/breathwork',
  path: '/breathwork',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActionPlanRoute = AppActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIndexRoute = AppResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPhasesIndexRoute = AppPhasesIndexRouteImport.update({
  id: '/phases/',
  path: '/phases/',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningIndexRoute = AppLearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainGamesIndexRoute = AppBrainGamesIndexRouteImport.update({
  id: '/brain-games/',
  path: '/brain-games/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIdRoute = AppResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdRoute = AppRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPhasesSlugRoute = AppPhasesSlugRouteImport.update({
  id: '/phases/$slug',
  path: '/phases/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningIdRoute = AppLearningIdRouteImport.update({
  id: '/learning/$id',
  path: '/learning/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainGamesIdRoute = AppBrainGamesIdRouteImport.update({
  id: '/brain-games/$id',
  path: '/brain-games/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRequestRoute = AppAppointmentsRequestRouteImport.update({
  id: '/appointments/request',
  path: '/appointments/request',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminResourcesRoute = AppAdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/action-plan': typeof AppActionPlanRoute
  '/education': typeof AppEducationRoute
  '/substitutes': typeof AppSubstitutesRoute
  '/hemp': typeof AppHempRoute
  '/handouts': typeof AppHandoutsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/breathwork': typeof AppBreathworkRoute
  '/caregiver': typeof AppCaregiverRoute
  '/dashboard': typeof AppDashboardRoute
  '/hard-day': typeof AppHardDayRoute
  '/help': typeof AppHelpRoute
  '/journal': typeof AppJournalRoute
  '/movement': typeof AppMovementRoute
  '/notes': typeof AppNotesRoute
  '/pantry-audit': typeof AppPantryAuditRoute
  '/print-center': typeof AppPrintCenterRoute
  '/program-dates': typeof AppProgramDatesRoute
  '/progress': typeof AppProgressRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/start-here': typeof AppStartHereRoute
  '/today': typeof AppTodayRoute
  '/toxic-load': typeof AppToxicLoadRoute
  '/videos': typeof AppVideosRoute
  '/week': typeof AppWeekRoute
  '/admin/resources': typeof AppAdminResourcesRoute
  '/appointments/request': typeof AppAppointmentsRequestRoute
  '/brain-games/$id': typeof AppBrainGamesIdRoute
  '/learning/$id': typeof AppLearningIdRoute
  '/phases/$slug': typeof AppPhasesSlugRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/brain-games/': typeof AppBrainGamesIndexRoute
  '/learning/': typeof AppLearningIndexRoute
  '/phases/': typeof AppPhasesIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/resources/': typeof AppResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/action-plan': typeof AppActionPlanRoute
  '/education': typeof AppEducationRoute
  '/substitutes': typeof AppSubstitutesRoute
  '/hemp': typeof AppHempRoute
  '/handouts': typeof AppHandoutsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/breathwork': typeof AppBreathworkRoute
  '/caregiver': typeof AppCaregiverRoute
  '/dashboard': typeof AppDashboardRoute
  '/hard-day': typeof AppHardDayRoute
  '/help': typeof AppHelpRoute
  '/journal': typeof AppJournalRoute
  '/movement': typeof AppMovementRoute
  '/notes': typeof AppNotesRoute
  '/pantry-audit': typeof AppPantryAuditRoute
  '/print-center': typeof AppPrintCenterRoute
  '/program-dates': typeof AppProgramDatesRoute
  '/progress': typeof AppProgressRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/start-here': typeof AppStartHereRoute
  '/today': typeof AppTodayRoute
  '/toxic-load': typeof AppToxicLoadRoute
  '/videos': typeof AppVideosRoute
  '/week': typeof AppWeekRoute
  '/admin/resources': typeof AppAdminResourcesRoute
  '/appointments/request': typeof AppAppointmentsRequestRoute
  '/brain-games/$id': typeof AppBrainGamesIdRoute
  '/learning/$id': typeof AppLearningIdRoute
  '/phases/$slug': typeof AppPhasesSlugRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/brain-games': typeof AppBrainGamesIndexRoute
  '/learning': typeof AppLearningIndexRoute
  '/phases': typeof AppPhasesIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/resources': typeof AppResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/action-plan': typeof AppActionPlanRoute
  '/_app/education': typeof AppEducationRoute
  '/_app/substitutes': typeof AppSubstitutesRoute
  '/_app/hemp': typeof AppHempRoute
  '/_app/handouts': typeof AppHandoutsRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/breathwork': typeof AppBreathworkRoute
  '/_app/caregiver': typeof AppCaregiverRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hard-day': typeof AppHardDayRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/movement': typeof AppMovementRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/pantry-audit': typeof AppPantryAuditRoute
  '/_app/print-center': typeof AppPrintCenterRoute
  '/_app/program-dates': typeof AppProgramDatesRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/start-here': typeof AppStartHereRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/toxic-load': typeof AppToxicLoadRoute
  '/_app/videos': typeof AppVideosRoute
  '/_app/week': typeof AppWeekRoute
  '/_app/admin/resources': typeof AppAdminResourcesRoute
  '/_app/appointments/request': typeof AppAppointmentsRequestRoute
  '/_app/brain-games/$id': typeof AppBrainGamesIdRoute
  '/_app/learning/$id': typeof AppLearningIdRoute
  '/_app/phases/$slug': typeof AppPhasesSlugRoute
  '/_app/recipes/$id': typeof AppRecipesIdRoute
  '/_app/resources/$id': typeof AppResourcesIdRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/brain-games/': typeof AppBrainGamesIndexRoute
  '/_app/learning/': typeof AppLearningIndexRoute
  '/_app/phases/': typeof AppPhasesIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/resources/': typeof AppResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/action-plan'
    | '/education'
    | '/substitutes'
    | '/hemp'
    | '/handouts'
    | '/admin'
    | '/breathwork'
    | '/caregiver'
    | '/dashboard'
    | '/hard-day'
    | '/help'
    | '/journal'
    | '/movement'
    | '/notes'
    | '/pantry-audit'
    | '/print-center'
    | '/program-dates'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/start-here'
    | '/today'
    | '/toxic-load'
    | '/videos'
    | '/week'
    | '/admin/resources'
    | '/appointments/request'
    | '/brain-games/$id'
    | '/learning/$id'
    | '/phases/$slug'
    | '/recipes/$id'
    | '/resources/$id'
    | '/appointments/'
    | '/brain-games/'
    | '/learning/'
    | '/phases/'
    | '/recipes/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/action-plan'
    | '/education'
    | '/substitutes'
    | '/hemp'
    | '/handouts'
    | '/admin'
    | '/breathwork'
    | '/caregiver'
    | '/dashboard'
    | '/hard-day'
    | '/help'
    | '/journal'
    | '/movement'
    | '/notes'
    | '/pantry-audit'
    | '/print-center'
    | '/program-dates'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/start-here'
    | '/today'
    | '/toxic-load'
    | '/videos'
    | '/week'
    | '/admin/resources'
    | '/appointments/request'
    | '/brain-games/$id'
    | '/learning/$id'
    | '/phases/$slug'
    | '/recipes/$id'
    | '/resources/$id'
    | '/appointments'
    | '/brain-games'
    | '/learning'
    | '/phases'
    | '/recipes'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sign-in'
    | '/_app/action-plan'
    | '/_app/education'
    | '/_app/substitutes'
    | '/_app/hemp'
    | '/_app/handouts'
    | '/_app/admin'
    | '/_app/breathwork'
    | '/_app/caregiver'
    | '/_app/dashboard'
    | '/_app/hard-day'
    | '/_app/help'
    | '/_app/journal'
    | '/_app/movement'
    | '/_app/notes'
    | '/_app/pantry-audit'
    | '/_app/print-center'
    | '/_app/program-dates'
    | '/_app/progress'
    | '/_app/routines'
    | '/_app/settings'
    | '/_app/start-here'
    | '/_app/today'
    | '/_app/toxic-load'
    | '/_app/videos'
    | '/_app/week'
    | '/_app/admin/resources'
    | '/_app/appointments/request'
    | '/_app/brain-games/$id'
    | '/_app/learning/$id'
    | '/_app/phases/$slug'
    | '/_app/recipes/$id'
    | '/_app/resources/$id'
    | '/_app/appointments/'
    | '/_app/brain-games/'
    | '/_app/learning/'
    | '/_app/phases/'
    | '/_app/recipes/'
    | '/_app/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/week': {
      id: '/_app/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AppWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toxic-load': {
      id: '/_app/toxic-load'
      path: '/toxic-load'
      fullPath: '/toxic-load'
      preLoaderRoute: typeof AppToxicLoadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/start-here': {
      id: '/_app/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof AppStartHereRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/program-dates': {
      id: '/_app/program-dates'
      path: '/program-dates'
      fullPath: '/program-dates'
      preLoaderRoute: typeof AppProgramDatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print-center': {
      id: '/_app/print-center'
      path: '/print-center'
      fullPath: '/print-center'
      preLoaderRoute: typeof AppPrintCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry-audit': {
      id: '/_app/pantry-audit'
      path: '/pantry-audit'
      fullPath: '/pantry-audit'
      preLoaderRoute: typeof AppPantryAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movement': {
      id: '/_app/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof AppMovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hard-day': {
      id: '/_app/hard-day'
      path: '/hard-day'
      fullPath: '/hard-day'
      preLoaderRoute: typeof AppHardDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caregiver': {
      id: '/_app/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/breathwork': {
      id: '/_app/breathwork'
      path: '/breathwork'
      fullPath: '/breathwork'
      preLoaderRoute: typeof AppBreathworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-plan': {
      id: '/_app/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof AppActionPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/': {
      id: '/_app/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppResourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/phases/': {
      id: '/_app/phases/'
      path: '/phases'
      fullPath: '/phases/'
      preLoaderRoute: typeof AppPhasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/': {
      id: '/_app/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof AppLearningIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain-games/': {
      id: '/_app/brain-games/'
      path: '/brain-games'
      fullPath: '/brain-games/'
      preLoaderRoute: typeof AppBrainGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/$id': {
      id: '/_app/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof AppResourcesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id': {
      id: '/_app/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AppRecipesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/phases/$slug': {
      id: '/_app/phases/$slug'
      path: '/phases/$slug'
      fullPath: '/phases/$slug'
      preLoaderRoute: typeof AppPhasesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/$id': {
      id: '/_app/learning/$id'
      path: '/learning/$id'
      fullPath: '/learning/$id'
      preLoaderRoute: typeof AppLearningIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain-games/$id': {
      id: '/_app/brain-games/$id'
      path: '/brain-games/$id'
      fullPath: '/brain-games/$id'
      preLoaderRoute: typeof AppBrainGamesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/request': {
      id: '/_app/appointments/request'
      path: '/appointments/request'
      fullPath: '/appointments/request'
      preLoaderRoute: typeof AppAppointmentsRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/resources': {
      id: '/_app/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AppAdminResourcesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminResourcesRoute: typeof AppAdminResourcesRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminResourcesRoute: AppAdminResourcesRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppActionPlanRoute: typeof AppActionPlanRoute
  AppEducationRoute: typeof AppEducationRoute
  AppSubstitutesRoute: typeof AppSubstitutesRoute
  AppHempRoute: typeof AppHempRoute
  AppHandoutsRoute: typeof AppHandoutsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBreathworkRoute: typeof AppBreathworkRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHardDayRoute: typeof AppHardDayRoute
  AppHelpRoute: typeof AppHelpRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMovementRoute: typeof AppMovementRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPantryAuditRoute: typeof AppPantryAuditRoute
  AppPrintCenterRoute: typeof AppPrintCenterRoute
  AppProgramDatesRoute: typeof AppProgramDatesRoute
  AppProgressRoute: typeof AppProgressRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStartHereRoute: typeof AppStartHereRoute
  AppTodayRoute: typeof AppTodayRoute
  AppToxicLoadRoute: typeof AppToxicLoadRoute
  AppVideosRoute: typeof AppVideosRoute
  AppWeekRoute: typeof AppWeekRoute
  AppAppointmentsRequestRoute: typeof AppAppointmentsRequestRoute
  AppBrainGamesIdRoute: typeof AppBrainGamesIdRoute
  AppLearningIdRoute: typeof AppLearningIdRoute
  AppPhasesSlugRoute: typeof AppPhasesSlugRoute
  AppRecipesIdRoute: typeof AppRecipesIdRoute
  AppResourcesIdRoute: typeof AppResourcesIdRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppBrainGamesIndexRoute: typeof AppBrainGamesIndexRoute
  AppLearningIndexRoute: typeof AppLearningIndexRoute
  AppPhasesIndexRoute: typeof AppPhasesIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppResourcesIndexRoute: typeof AppResourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionPlanRoute: AppActionPlanRoute,
  AppEducationRoute: AppEducationRoute,
  AppSubstitutesRoute: AppSubstitutesRoute,
  AppHempRoute: AppHempRoute,
  AppHandoutsRoute: AppHandoutsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBreathworkRoute: AppBreathworkRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHardDayRoute: AppHardDayRoute,
  AppHelpRoute: AppHelpRoute,
  AppJournalRoute: AppJournalRoute,
  AppMovementRoute: AppMovementRoute,
  AppNotesRoute: AppNotesRoute,
  AppPantryAuditRoute: AppPantryAuditRoute,
  AppPrintCenterRoute: AppPrintCenterRoute,
  AppProgramDatesRoute: AppProgramDatesRoute,
  AppProgressRoute: AppProgressRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStartHereRoute: AppStartHereRoute,
  AppTodayRoute: AppTodayRoute,
  AppToxicLoadRoute: AppToxicLoadRoute,
  AppVideosRoute: AppVideosRoute,
  AppWeekRoute: AppWeekRoute,
  AppAppointmentsRequestRoute: AppAppointmentsRequestRoute,
  AppBrainGamesIdRoute: AppBrainGamesIdRoute,
  AppLearningIdRoute: AppLearningIdRoute,
  AppPhasesSlugRoute: AppPhasesSlugRoute,
  AppRecipesIdRoute: AppRecipesIdRoute,
  AppResourcesIdRoute: AppResourcesIdRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppBrainGamesIndexRoute: AppBrainGamesIndexRoute,
  AppLearningIndexRoute: AppLearningIndexRoute,
  AppPhasesIndexRoute: AppPhasesIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppResourcesIndexRoute: AppResourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
